//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace JobManagerInterfaces.XML {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rbadams.com/Automation/Package")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.rbadams.com/Automation/Package", IsNullable=false)]
    public partial class Package {
        
        private PathT mainDirectoryField;
        
        private PathT[] additionalSubDirectoriesField;
        
        private string dLLFileNameField;
        
        private string jobRunnerClassNameField;
        
        private string[] requiredJobPropertiesField;
        
        private PackageProperty[] propertiesField;
        
        private string[] requiredISOsField;
        
        /// <remarks/>
        public PathT MainDirectory {
            get {
                return this.mainDirectoryField;
            }
            set {
                this.mainDirectoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SubDirectory", IsNullable=false)]
        public PathT[] AdditionalSubDirectories {
            get {
                return this.additionalSubDirectoriesField;
            }
            set {
                this.additionalSubDirectoriesField = value;
            }
        }
        
        /// <remarks/>
        public string DLLFileName {
            get {
                return this.dLLFileNameField;
            }
            set {
                this.dLLFileNameField = value;
            }
        }
        
        /// <remarks/>
        public string JobRunnerClassName {
            get {
                return this.jobRunnerClassNameField;
            }
            set {
                this.jobRunnerClassNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PropertyName", IsNullable=false)]
        public string[] RequiredJobProperties {
            get {
                return this.requiredJobPropertiesField;
            }
            set {
                this.requiredJobPropertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Property", IsNullable=false)]
        public PackageProperty[] Properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ISOName", IsNullable=false)]
        public string[] RequiredISOs {
            get {
                return this.requiredISOsField;
            }
            set {
                this.requiredISOsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rbadams.com/Automation/Package")]
    public partial class PathT {
        
        private string pathField;
        
        private PathTPathType pathTypeField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PathTPathType PathType {
            get {
                return this.pathTypeField;
            }
            set {
                this.pathTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.rbadams.com/Automation/Package")]
    public enum PathTPathType {
        
        /// <remarks/>
        BuildRelative,
        
        /// <remarks/>
        Absolute,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.rbadams.com/Automation/Package")]
    public partial class PackageProperty {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}
