//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace JobManagerInterfaces.XML {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rbadams.com/Automation/Sequence")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.rbadams.com/Automation/Sequence", IsNullable=false)]
    public partial class Sequence {
        
        private string[] packageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Package")]
        public string[] Package {
            get {
                return this.packageField;
            }
            set {
                this.packageField = value;
            }
        }
    }
}
